### ISSUE TITLE
Task: CI Script for Postman Unit Testing

### ISSUE THREAD

**Issue by PokeJofeJr4th** [rit-sse/WebsiteTheSSEquel#106]
# Template Instructions

Use this template to create a new task item.

1. Copy this template and paste it into a new item project item under backlog.
2. Fill in the placeholders with your own information.
3. Remove these instructions from the item (the horizontal line and above)
4. Add any additional details or context that may be helpful.
5. Assign the issue to a team member or yourself.
6. Use the checkboxes to track progress and ensure all requirements are met before marking the issue as complete.

---

# CI Script for Postman Testing

## Description

Create a script that can be used to run tests for API CRUD endpoints through Github Actions.

## Subtasks

- [x] Set up Github Actions environment and background processes
- [x] Create tests in Postman
- [x] Run postman tests on Github Actions and report results

## Acceptance Criteria

- [x] Github Actions runs API tests
- [x] New tests added to a specified folder are included in the Actions run
- [ ] All API routes have tests created
