### ISSUE TITLE
Task: Develop Entity Relationship Diagram

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#18]
# <Task Title># Develop Entity Relationship Diagram

As a **developer**, I want **create an entity relationship diagram**, so that **I can establish schema for database objects**.

## Description

Analyze the project requirements, establish the necessary tables and fields, and develop an entity relationship diagram to represent the structure of the database.

## Subtasks

- [x] Analyze project requirements for a list of needed tables and fields
- [x] Run this list by me (Ryan Webb) for feedback
- [x] Develop entity relationship diagram
- [x] Update document as design changes

## Acceptance Criteria

- [ ] [Acceptance Criteria 1]
- [ ] [Acceptance Criteria 2]
- [ ] [Acceptance Criteria 3]

**Comment by 2nPlusOne** [comment]
Looks good for an initial pass! The feedback from professors was very helpful. 

Gonna close this task, Great job!
