### ISSUE TITLE
Task: Update domain model in draw.io

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#21]
# Update the domain model and recreate it in draw.io

## Description

Recreate the domain model in draw.io, and update it as necessary. 

## Subtasks

- [x] create draw.io document
- [ ] Migrate domain model from lucid
- [ ] Update domain model to more accurately reflect the problem space

## Acceptance Criteria

- [ ] subtasks finished

## Links to Related Documents

- [ ] link here
