### ISSUE TITLE
Epic: About Pages

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#27]
# Epic: Static About Pages

## User Stories

List the user stories that are associated with this epic.

- [x] As a **visitor**, I want **to see general information about the SSE on the About Us page** so that **I can learn more about the organization**. #link
- [x] As a **visitor**, I want to **visit the Getting Involved page** so that I can **learn more about different ways I can get involved in the organization’s activities**.
 #link
- [x] As a **visitor**, I want to **visit the Leadership page** so that **I can learn about present and past leadership teams**. #link
- [x] As a **visitor**, I want to **view the Constitution page** so that **I can learn the ins and outs of the SSE’s structure and operation**.
- [x] As a **visitor**, I want to **visit the Primary Officer’s Policy page** so that I can **explore the responsibilities of each officer role within the SSE**.
- [x] As a **visitor**, I want to **visit the committees page** so that I can **read detailed information on each SSE committee including a brief description of the committee’s goals**.

## Technical Requirements

List the technical requirements for this epic.

- [ ] [Requirement 1]

## Design Considerations

List the design considerations for this epic.

- [ ] [Consideration 1]
- [ ] [Consideration 2]
- [ ] [Consideration 3]

## Dependencies

List the epics that this epic depends on.

- [ ] Leadership page depends on the backend API route for accessing officer data. <replace this with the specific epic and link once created>

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
