### ISSUE TITLE
Task: Update Color Scheme using DaisyUI data-theme

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#36]
#  Update Color Scheme using DaisyUI data-theme

## Description

The site should use color schemes set up with the DaisyUI tailwind plugin, this way we can use semantic color names like "primary" or "secondary", and easily switch between light and dark modes.

## Subtasks

- [x] Add color themes (light mode and dark mode) by modifying the daisyUI section of the tailwind config file
- [x] Replace static tailwind colors with the semantic daisyUI color names
- [x] Use next-themes to implement a dark mode toggle button

## Acceptance Criteria

- [x] Primary/secondary/accent colors are derived from the logo
- [x] Darkmode toggle button should not produce any flickering, flashing, or layout shifts
- [x] The SSE logo should be legible in both light mode and dark mode
