### ISSUE TITLE
Task: Document Database Schema

### ISSUE THREAD

**Issue by sjv01180** [rit-sse/WebsiteTheSSEquel#39]
# Document Database Schema

Document the tables and their relationships on a Google doc for team members to reference and review.

## Subtasks

- [ ] Write a rough draft of schema documentation
- [ ] Review/Revise draft with backend team
- [ ] Construct final draft

## Acceptance Criteria

- [ ] Documentation should cover all tables
- [ ] Feedback from backend team
- [ ] Revise document for final draft

**Comment by 2nPlusOne** [comment]
The ERD fulfills this purpose, and it was merged recently. I'll close this issue for now. Feel free to create another issue when the schema is updated or added to.
