### ISSUE TITLE
Task: Create "quote" Table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#41]
# <quote>

## Description

Create "quote" table within the SSE Website back end.

## Subtasks
- [ ] Document "quote" table
- [ ] create PK column
- [ ] create date_added column 
- [ ] create quote column
- [ ] create user_id column
- [ ] create author column
- [ ] create user relation

## Acceptance Criteria
- [ ] PK retrievable
- [ ] date_added retrievable
- [ ] quote retrievable
- [ ] user_id retrievable
- [ ] author retrievable
```
