### ISSUE TITLE
Task Create "officer" Table

### ISSUE THREAD

**Issue by Malam2704** [rit-sse/WebsiteTheSSEquel#42]
# Create "officer" Table

## Description

Create "officer" table within the SSE Website back end.

## Subtasks

- [ ] Document "officer" table
- [ ] Create PK column
- [ ] Create user_id column
- [ ] Create position column
- [ ] Create is_active column
- [ ] Create start_date column
- [ ] Create end_date column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] user_id is retrievable
- [ ] Position is retrievable 
- [ ] is_active is retrievable
- [ ] start_date is retrievable
- [ ] end_date is retrievable
```
