### ISSUE TITLE
Task: Create "user" Table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#43]
# Create User Table

## Description

Create "user" table within the SSE Website back end.

## Subtasks

- [ ] Document "user" table
- [ ] Create first_name column
- [ ] Create last_name column
- [ ] Create email column
- [ ] Create is_member column
- [ ] Create profile_pic column
- [ ] Create accounts Array Column
- [ ] Create sessions Array Column

## Acceptance Criteria

- [ ] first_name is retrievable
- [ ] last_name is retrievable
- [ ] email is retrievable
- [ ] is_member is retrievable
- [ ] profile_pic is retrievable
- [ ] github is retrievable
- [ ] linkedIn is retrievable
- [ ] deactivation_date is retrievable
```
