### ISSUE TITLE
Task: Create "mentor" table

### ISSUE THREAD

**Issue by sjv01180** [rit-sse/WebsiteTheSSEquel#44]
# Create "mentor" Table

## Description

Create "mentor" table within the SSE Website back end.

## Subtasks

- [ ] Document "mentor" table
- [x] Create PK column
- [x] Create id_serial column
- [x] Create user_id column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] id_serial is retrievable
- [ ] user_id is retrievable
```
