### ISSUE TITLE
Create "mentor_skill" Table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#45]
# Create "mentor skill" Table

## Description

Create "mentor_skill" table within the SSE Website back end.

## Subtasks

- [ ] Document "mentor_skill" table
- [ ] create PK column
- [ ] create user_id column
- [ ] create skill_id column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] user_id is retrievable
- [ ] skill_id is retrievable
```
