### ISSUE TITLE
Task Create "officer_position" Table

### ISSUE THREAD

**Issue by Malam2704** [rit-sse/WebsiteTheSSEquel#46]
# Create "officer_position" Table

## Description

Create "officer_position" table within the SSE Website back end.

## Subtasks

- [ ] Document "officer_position" table
- [ ] Create title column
- [ ] Create is_primary column
- [ ] Create email column

## Acceptance Criteria

- [ ] title is retrievable
- [ ] is_primary is retrievable
- [ ] email is retrievable
```
