### ISSUE TITLE
Task Create "hour_block" table

### ISSUE THREAD

**Issue by Malam2704** [rit-sse/WebsiteTheSSEquel#47]
# Create "hour_block" Table

## Description

Create "hour_block" table within the SSE Website back end.

## Subtasks

- [ ] Document "hour_block" table
- [ ] Create weekday column
- [ ] Create start_time column
- [ ] Create end_time column

## Acceptance Criteria

- [ ] weekday is retrieveable
- [ ] start_time is retrievable
- [ ] end_time is retrievable
```
