### ISSUE TITLE
Task: Create "skill" Table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#48]
# Create "skill" Table

## Description

Create "skill" table within the SSE Website back end.

## Subtasks

- [ ] Document "skill" table
- [ ] Create PK column
- [ ] Create skill column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] skill is retrievable
```
