### ISSUE TITLE
Task: Create "course" Table

### ISSUE THREAD

**Issue by sjv01180** [rit-sse/WebsiteTheSSEquel#49]
# Create "course" Table

## Description

Create "course" table within the SSE Website back end.

## Subtasks

- [ ] Document "course" table
- [ ] Create PK column
- [ ] Create id_serial column
- [ ] Create title column
- [ ] Create department column
- [ ] Create code column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] id_serial is retrievable
- [ ] title is retrievable
- [ ] department is retrievable
- [ ] code is retrievable
```
