### ISSUE TITLE
Task: Create "schedule" table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#50]
# Create "schedule" Table

## Description

Create "schedule" table within the SSE Website back end.

## Subtasks

- [ ] Document "schedule" table
- [x] Create PK column
- [x] Create mentor_id column
- [x] Create hour_block_id column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] mentor_id is retrievable
- [ ] hour_block_id is retrievable
