### ISSUE TITLE
Task: Create "course_taken" Table

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#51]
# Create "course_taken" Table

## Description

Create "course_taken" table within the SSE Website back end.

## Subtasks

- [ ] Document "course_taken" table
- [ ] Create PK column
- [ ] Create mentor_id column
- [ ] Create course_id column

## Acceptance Criteria

- [ ] PK is retrievable
- [ ] mentor_id is retrievable
- [ ] course_id is retrievable
