### ISSUE TITLE
Epic: API CRUD Commands

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#62]

**Comment by joebaillie21** [comment]
# API Create, Read, Update, and Delete Commands 

## User Stories

List the user stories that are associated with this epic.

- [ ] As a front-end dev, I want perform CRUD on the USER table, so that I can manage the USER table.
- [ ] As a front-end dev, I want perform CRUD on the OFFICER table, so that I can manage the OFFICER table.
- [ ] As a front-end dev, I want perform CRUD on the OFFICER POSITION table, so that I can manage the OFFICER POSITION table.
- [ ] As a front-end dev, I want perform CRUD on the SCHEDULE table, so that I can manage the SCHEDULE table.
- [ ] As a front-end dev, I want perform CRUD on the MENTOR table, so that I can manage the MENTOR table.
- [ ] As a front-end dev, I want perform CRUD on the COURSE table, so that I can manage the COURSE table.
- [ ] As a front-end dev, I want perform CRUD on the COURSE TAKEN table, so that I can manage the COURSE TAKEN table.
- [ ] As a front-end dev, I want perform CRUD on the SKILL table, so that I can manage the SKILL table.
- [ ] As a front-end dev, I want perform CRUD on the MENTOR SKILL table, so that I can manage the MENTOR SKILL table.

These will be adjusted following a meeting with the product owner to determine what features they do and don't want to be editable


## Technical Requirements

List the technical requirements for this epic.

- [ ]Schema complete
## Design Considerations

List the design considerations for this epic.

- [ ] What tables need all 4 functions
- [ ] What tables will only need some functionality
- [ ] What should be readable

## Dependencies

- [ ] Auth to determine who can access the API

- [ ] [Epic 1]
- [ ] [Epic 2]
- [ ] [Epic 3]

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
- [ ] [Document 2]
- [ ] [Document 3]
```
