### ISSUE TITLE
Epic: Go Links

### ISSUE THREAD

**Issue by 2nPlusOne** [rit-sse/WebsiteTheSSEquel#67]
# Go Links

## User Stories

List the user stories that are associated with this epic.

- [ ] As a user logged in as an officer, I want to have access to a Go Links management page so that I can add, remove, edit, and pin go links.
- [ ] As a user, I want to have access to a Go Links page so that I can view and click on an active link so that I can view the linked site.
- [ ] As a user logged in as an officer, I want to have my link authenticated before it’s posted to the site so that dead links aren’t posted accidentally. 
- [ ] As a developer, I want to have API routes that allow me to perform CRUD operations on the Go Links resource in the database so that I can build Go Links-related UI features.

## Technical Requirements

List the technical requirements for this epic.

- [ ] Authentication is set up, allowing role-based page/route authorization via the user's session
- [ ] Go links database resource exists

## Design Considerations

List any special design considerations for this epic.

- [ ] How do we display pinned go links? Should they be displayed at the top of the list, have a different color scheme, or be displayed off to the side/at the top of the page separate from the rest of the links?

## Dependencies

List any epics that this epic depends on.

- [ ] User Authentication

## Design Documents

List the design documents associated with this epic.

- [ ] [Document 1]
- [ ] [Document 2]
