### ISSUE TITLE
Task: Schema Test Data

### ISSUE THREAD

**Issue by joebaillie21** [rit-sse/WebsiteTheSSEquel#73]
# Schema Test Data

## Description

Seed the DB with data for testing

## Subtasks

- [x] Define seed data
- [x] Add seed data

## Acceptance Criteria

- [x] All tables have 3 unique rows of data
